parameters:
  colemando_ratchetio.twig_extension.class: Colemando\RatchetioBundle\Twig\RatchetioExtension
  colemando_ratchetio.exception_listener.class: Colemando\RatchetioBundle\EventListener\ExceptionListener

services:
  colemando_ratchetio.twig_extension:
    class: %colemando_ratchetio.twig_extension.class%
    arguments:
      - %colemando_ratchetio.access_token%
    tags:
      - { name: twig.extension }

  colemando_ratchetio.exception_listener:
    class: %colemando_ratchetio.exception_listener.class%
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

